services:
  graceful-web:
    build:
      context: graceful-florist-web
      dockerfile: Dockerfile
    container_name: angular-nginx
    ports:
      - "4200:4200"
  graceful-service:
    build:
      context: graceful-florist-services
      dockerfile: Dockerfile
    container_name: spring-boot-21
    environment:
      TZ: Asia/Jakarta
      POSTGRES_HOST: graceful-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET: ${MINIO_ROOT_PASSWORD}
    ports:
      - "8080:8080"
  graceful-db:
    image: postgres:16
    restart: always
    environment:
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./graceful-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  minio:
    image: quay.io/minio/minio
    container_name: graceful-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}